---
- name: Converge
  hosts: all
  vars:
    struktur_spreed_from_source: true
    struktur_spreed_build_version: "{{ molecule_struktur_spreed_build_version | default('HEAD') }}"
    golang_version: "{{ molecule_golang_version | default('1.23.5') }}"
    golang_install_dir: /opt/go
  pre_tasks:
    - name: debug VARs
      ansible.builtin.debug:
        var: struktur_spreed_build_version
    - name: debug VARs
      ansible.builtin.debug:
        var: golang_version

  roles:
    - gantsign.golang
    - rls.nextcloud-spreed-signaling
