---
- name: Converge
  hosts: all
  vars:
    struktur_spreed_from_source: true
    struktur_spreed_build_version: "{{ lookup('ansible.builtin.env', 'molecule_struktur_spreed_build_version') }}"
    golang_version: "{{ lookup('ansible.builtin.env', 'molecule_golang_version', default='1.23.5') }}"
    golang_install_dir: /opt/go
  pre_tasks:
    - name: debug VAR struktur_spreed_build_version
      ansible.builtin.debug:
        var: struktur_spreed_build_version
    - name: debug VAR golang_version
      ansible.builtin.debug:
        var: golang_version
  roles:
    - gantsign.golang
    - rls.nextcloud-spreed-signaling
