---
- name: Converge
  hosts: all
  vars:
    struktur_spreed_from_source: true
    struktur_spreed_build_version: "${molecule_struktur_spreed_build_version:-HEAD}"
    golang_version: "${molecule_golang_version:-1.23.5}"
    golang_install_dir: /opt/go
  roles:
    - gantsign.golang
    - rls.nextcloud-spreed-signaling
