---

- name: ensure the deb packages are uninstalled
  ansible.builtin.apt:
    name: "{{ debian_spreed_apt_pkg + struktur_spreed_apt_pkg }}"
    state: absent
    purge: true
    autoremove: true

- name: install build requirements
  ansible.builtin.apt:
    name: "{{ struktur_spreed_build_requirememnts }}"
    update_cache: true

- name: clone repo nextcloud-spreed-signaling
  ansible.builtin.git:
    repo: https://github.com/strukturag/nextcloud-spreed-signaling.git
    dest: /var/tmp/nextcloud-spreed-signaling
    version: "{{ struktur_spreed_build_version | default(omit) }}"
    update: false

- name: build nextcloud-spreed-signaling using golang_install_dir {{ golang_install_dir }}
  ansible.builtin.shell: PATH={{ golang_install_dir }}/bin:$PATH make build
  args:
    chdir: /var/tmp/nextcloud-spreed-signaling
    creates: /var/tmp/nextcloud-spreed-signaling/bin/signaling
  when: golang_install_dir is defined

- name: build nextcloud-spreed-signaling
  ansible.builtin.command: make build
  args:
    chdir: /var/tmp/nextcloud-spreed-signaling
    creates: /var/tmp/nextcloud-spreed-signaling/bin/signaling
  when: not golang_install_dir is defined

- name: create user
  ansible.builtin.user:
    name: nextcloud-spreed-signaling
    system: true
    shell: /usr/sbin/nologin

- name: install nextcloud-spreed-signaling
  ansible.builtin.copy:
    src: /var/tmp/nextcloud-spreed-signaling/bin/signaling
    dest: /usr/sbin/nextcloud-spreed-signaling
    remote_src: true
    mode: "0750"
    owner: root
    group: nextcloud-spreed-signaling

- name: create cfg dir for nextcloud-spreed-signaling
  ansible.builtin.file:
    path: /etc/nextcloud-spreed-signaling
    state: directory
    mode: "0750"
    owner: root
    group: nextcloud-spreed-signaling

- name: create signaling.service
  ansible.builtin.template:
    src: nextcloud-spreed-signaling.service.j2
    dest: /lib/systemd/system/nextcloud-spreed-signaling.service
    mode: "0644"
    owner: root
    group: root
  register: service

- name: enable nextcloud-spreed-signaling service
  ansible.builtin.systemd:
    daemon_reload: true
    name: nextcloud-spreed-signaling
    enabled: true
    masked: false
  notify: restart nextcloud-spreed-signaling
