---

- name: ensure packages are installed
  ansible.builtin.apt:
    name:
      - gpg
      - gpg-agent

- name: add spreed repo key
  ansible.builtin.get_url:
    url: "{{ struktur_spreed_apt_key_url }}"
    dest: "/usr/share/keyrings/{{ struktur_spreed_apt_key_name }}"
    owner: root
    mode: "0644"

- name: add spreed repository
  ansible.builtin.copy:
    content: "{{ struktur_spreed_apt_repo }}\n"
    dest: /etc/apt/sources.list.d/nextcloud-spreed-repository.list
    owner: root
    group: root
    mode: "0644"

- name: pin spreed repository
  ansible.builtin.copy:
    src: nextcloud
    dest: /etc/apt/preferences.d/nextcloud
    owner: root
    group: root
    mode: "0644"

- name: install spreed packages
  ansible.builtin.apt:
    name: "{{ struktur_spreed_apt_pkg }}"
    update_cache: true

...
