---

- name: install  nextcloud-spreed-signaling HPB from debian
  ansible.builtin.include_tasks: hpb-deb-orig.yml
  when:
    - not struktur_spreed_from_source | default(false)
    - struktur_spreed_customerid == 'UNDEFINED'

- name: install struktur spreed HPB from package
  ansible.builtin.include_tasks: hpb-deb-struktur.yml
  when:
    - not struktur_spreed_from_source | default(false)
    - not struktur_spreed_customerid == 'UNDEFINED'

- name: install struktur spreed HPB from source
  ansible.builtin.include_tasks: hpb-src.yml
  when:
    - struktur_spreed_from_source | default(false)
    - struktur_spreed_customerid == 'UNDEFINED'

- name: install and configure nats-server
  ansible.builtin.include_tasks: nats.yml
  when: struktur_spreed_customerid == 'UNDEFINED'

- name: install and configure janus
  ansible.builtin.include_tasks: janus.yml

- name: configure nctalk signaling service
  ansible.builtin.template:
    src: nextcloud-spreed-signaling-server.conf.j2
    dest: /etc/nextcloud-spreed-signaling/server.conf
    mode: "0640"
    owner: "{{ signaling_user | default('nextcloud-spreed-signaling') }}"
    group: root
  notify: restart nextcloud-spreed-signaling

- name: fix late restart of janus via cron
  ansible.builtin.copy:
    src: fixjanus
    dest: /etc/cron.d/fixjanus
    owner: root
    group: root
    mode: "0644"

# TODO: add turn and signaling server on nextcloud site via occ
