---
# nats

- name: install nats-server from {{ nats_download_url }}
  ansible.builtin.apt:
    deb: "{{ nats_download_url }}"
  when: not nats_use_debian

- name: install nats-server
  ansible.builtin.apt:
    name: "{{ nats_deb }}"
  when: nats_use_debian

- name: service user for nats-server
  ansible.builtin.user:
    name: nats
    system: true
    shell: /usr/sbin/nologin

- name: create nats-server.conf
  ansible.builtin.template:
    src: nats-server.conf.j2
    dest: /etc/nats-server.conf
    mode: "0640"
    owner: root
    group: nats
    backup: true
  notify: restart nats-server

- name: create nats-server.service
  ansible.builtin.template:
    src: nats-server.service.j2
    dest: /lib/systemd/system/nats-server.service
    mode: "0644"
    owner: root
    group: root
  when: not nats_use_debian

- name: enable nats-server service
  ansible.builtin.systemd:
    daemon_reload: true
    name: nats-server
    enabled: true
    masked: false

- name: start nats-server
  ansible.builtin.service:
    name: nats-server
    state: started
