---
name: ansible-lint
on:
  pull_request:
  push:
  schedule:
    - cron: "45 6 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run ansible-lint
        uses: ansible/ansible-lint@v25.1.3
